# Generated by Django 3.1.5 on 2021-01-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='phone_number',
            field=models.IntegerField(blank=True, default='0700100100', max_length=15),
        ),
    ]
