# Generated by Django 3.1.5 on 2021-01-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor',
            name='phone_number',
            field=models.IntegerField(blank=True, default='0700100100'),
        ),
    ]
